language: ruby
rvm:
- 2.1

install: 
  - gem install bundler 
  - gem install ruby_dep -v 1.3.1
  - gem install jekyll
script: bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master