language: ruby
rvm:
- 2.2
install:
- gem install bundler
- gem install jekyll
script: bundle exec jekyll build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_e37f7d53ff65_key -iv $encrypted_e37f7d53ff65_iv
  -in deploy_key.enc -out deploy_key -d
