deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  matrix:
    secure: zpLOowe4a3NpqkZ5OW64zaJw+JH/78jGSn8iKYBOGvUni9PHOyLp1EYfHVHEmcu1XC2TFHHpBF+opFydyBmI6iHnUinxO8iz5WVHEL2LEhGRY1H2+YS7uawl3akDLCKdTw+Wi7nGLeqzeXUJB8QNlBzRttlEj+yGyYgzaeh5B7I7XchEJL8J7dxmvwtPYMrqoIzD0neYH/Au+9rUYsmNmxc/Dy5oG265qS1tmz/DoZq/3eLA7E+XmB8cNVICHHjt7IEbq47BG5H8b1y7j1tK4OhXsAe7jnO3RbORvWFdI2modEGmCk7Ae/oaeYh+cFVZ28tHcUPa+ONMXM228pLDabyr7ggYJwxKaqyS1Y398mjlV9nXVD/0Q6mHVbiGRuSvFjT5oyokHM5wTPW0kwquTDuk/hzslP71fa+uO3r3EDS7qP91zbxVUkCaDmTHW7zKqQgCI8+CLHiS40G6jzQpbnRNIHCjfep/DJm6Sco0KavvTYoxBMyP93mmhnwaa0BZa7YtldAf8vUEwnYEYpmLRsEfi0391IolR0FgOY2UHEDwciQXd48wmCLJ0m8IqcnosgkJCJ8Zi50V2NdQqp/nOQzuyXpjN7h2d/vMLXAxwCmoutxbbJGW6Td3usFQeF4Lrz4Vtg32EN2sxKVrPYtKpoJtfL6ki/uzno+fQXEi8F8=
before_install:
- openssl aes-256-cbc -K $encrypted_e37f7d53ff65_key -iv $encrypted_e37f7d53ff65_iv
  -in deploy_key.enc -out deploy_key -d
