deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_e37f7d53ff65_key -iv $encrypted_e37f7d53ff65_iv
  -in deploy_key.enc -out deploy_key -d
