# Site settings
title: molecule.github.io
email: molecule@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  testbed for case study publication
#url: the base hostname & protocol for your site
twitter_username: fakepaperclilps
github_username:  molecule
encoding: utf-8

# Build settings
# markdown: redcarpet
# highlighter: pygments
# extensions: [tables fenced_code_blocks]

exclude: [vendor]
kramdown:
   input: GFM
gems:
  - jekyll-sitemap