# dependencies / links
highlighter: rouge
permalink: pretty
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

# setup
# access this data with site.date. eg: {{ site.title }}
# baseurl: https://molecule.github.io

title: Molly Jane Nicholas
dev_url: localhost:4000
port: 4013
keywords: Molly Jane Nicholas, berkeley, human computer interaction, performance, puppeteering, computer science, hci
desc: >
  Molly Nicholas is a PhD student studying Human Computer Interaction 
  with Eric Paulos in the Computer Science department at UC Berkeley. 
  She is particularly interested in exploring how issues of politics, 
  identity, and education intersect with new media studies and 
  erformance studies.  Previously, she worked for two years as a 
  Software Engineer at Qualcomm, where she developed FIRST Robotics’ 
  new robotics platform. She is also a dancer, puppeteer, Clown 
  Conservatory-trained clown, singer, and casual contortionist living 
  in Berkeley, CA.  Molly received her B.A. from the University of 
  California, Berkeley with a double major in Computer Science and C
  ognitive Science in 2014.

# owner
author:
  name: Molly Jane Nicholas
  email: molecule@berkeley.edu
  github: https://github.com/molecule
  twitter: https://twitter.com/FakepaperClips

# site data
collections:
  post: {output: true}
  project: {output: true}
